version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/react-app
hooks:
  ApplicationStop:
    - location:
      timeout: 300
      runas: root
      content: |
        sudo systemctl stop nginx
  AfterInstall:
    - location:
      timeout: 300
      runas: root
      content: |
        sudo chown -R ubuntu:ubuntu /var/www/react-app
        sudo chmod -R 755 /var/www/react-app
  ApplicationStart:
    - location:
      timeout: 300
      runas: root
      content: |
        sudo systemctl start nginx
